### ISSUE TITLE
Composer support

### ISSUE THREAD

**Issue by YOzaz** [ramonztro/simple-scraper#2]
Any plans to add composer.json?

**Comment by ramonztro** [comment]
Never used it. I'll put that in my backlog. Thank you!

2015-07-08 5:53 GMT-03:00 Marijus Plančiūnas <notifications@github.com>:

> Any plans to add composer.json?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ramonztro/simple-scraper/issues/2>.
>



--

**Comment by YOzaz** [comment]
Well, it's like an Almanah for PHP projects at the moment - ad quite easy to implement :)
Just tag your release/version using GitHub tags, create composer.json file (you can take an example from [mine](https://github.com/YOzaz/Laravel-SwiftMailer/blob/master/composer.json)), namespace it (optionally), declare autoload (namespaced - PSR, not namespaced as it is - classmap), and submit to Packagist. That's it.

**Comment by YOzaz** [comment]
Can you please add your package to Packagist.org as well?
