### ISSUE TITLE
TITLE, HOST constants

### ISSUE THREAD

**Issue by YOzaz** [ramonztro/simple-scraper#3]
TITLE, HOST constants are missing.
```php
curl_setopt($ch,CURLOPT_USERAGENT,'Mozilla/5.0 (compatible; ' . TITLE . '/' . HOST . ')');
```

**Comment by ramonztro** [comment]
Thank you! I'll fix it later today! :)

2015-07-08 9:06 GMT-03:00 Marijus Plančiūnas <notifications@github.com>:

> TITLE, HOST constants are missing.
>
> curl_setopt($ch,CURLOPT_USERAGENT,'Mozilla/5.0 (compatible; ' . TITLE . '/' . HOST . ')');
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ramonztro/simple-scraper/issues/3>.
>



--

**Comment by ramonztro** [comment]
Done!
