### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by pbearne** [ramonztro/simple-scraper#6]
103 Warning: The use statement with non-compound name 'Exception' has no effect in /../../..//SimpleScraper.class.php on line 17

is this needed ?
use \Exception;

**Comment by ramonztro** [comment]
Well, this is just a warning, but you don't need that line. You can handle runtime errors as you like. Anyway, if you remove that line, I advise you to change lines that contain `throw new //...` for another error handling mechanism.

Just in case, you can turn off warnings visibility with `error_reporting(E_ALL ^ E_WARNING);`.

I hope that this does help! :)
